---
:global:
  componentName: fluentbit
  feature_goldenTests: false

docs/antora.yml:
  name: fluentbit
  title: fluentbit

LICENSE:
  year: 2020

.gitignore:
  additionalEntries:
    - jsonnetfile.json
